### ISSUE TITLE
REST API - Adding Keycloak authentication

### ISSUE THREAD

**Issue by valentinacupac** [valentinacupac/banking-kata-java#37]

**Comment by valentinacupac** [comment]
Thanks @adrianliz for this contribution! 

I merged the PR onto main and re-ran the tests locally (and also the tests were run on GitHub actions https://github.com/valentinacupac/banking-kata-java/actions).

5 tests fail. 

As an example, BankingApplicationTests.contextLoads()

```
Caused by: java.lang.IllegalStateException: Error processing condition on org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerJwtConfiguration$JwtDecoderConfiguration.jwtDecoderByJwkKeySetUri
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60)

Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'KEYCLOAK_REALM_URL' in value "${KEYCLOAK_REALM_URL}/protocol/openid-connect/certs"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:180)

```

Could you run it too locally and let me know what results you get, and also if you have any ideas regarding resolving this topic...

Thanks in advance!

**Comment by valentinacupac** [comment]
Sorry, the issue seems to be about Postgres now (so not related to KeyCloak), so I opened up a new ticket #57.

**Comment by valentinacupac** [comment]
Now the only remaining topic is the system test.

I run 

`PS C:\Users\valen\GitHub\valentinacupac\banking-kata-java> $env:POSTGRES_URL='jdbc:postgresql://localhost:5432/banking_kata'                                                                                                            
PS C:\Users\valen\GitHub\valentinacupac\banking-kata-java> $env:POSTGRES_USER='postgres'                                                                                                                                                
PS C:\Users\valen\GitHub\valentinacupac\banking-kata-java> $env:POSTGRES_PASSWORD='admin'                                                                                                                                               
PS C:\Users\valen\GitHub\valentinacupac\banking-kata-java> $env:KEYCLOAK_REALM_URL='http://localhost:10000/auth/realms/banking-kata'
PS C:\Users\valen\GitHub\valentinacupac\banking-kata-java> $env:KEYCLOAK_TEST_CLIENT_ID='test-client'
PS C:\Users\valen\GitHub\valentinacupac\banking-kata-java> $env:KEYCLOAK_TEST_CLIENT_SECRET='XXXX'
PS C:\Users\valen\GitHub\valentinacupac\banking-kata-java> ./gradlew build   `


I get this response:

`> Task :test

BankAccountControllerSystemTest > should_open_account_given_valid_request() FAILED
    org.springframework.web.reactive.function.client.WebClientRequestException at ExchangeFunctions.java:141
        Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException
            Caused by: java.net.ConnectException at Net.java:-2
2022-12-27 17:56:02.448  INFO 29688 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-12-27 17:56:02.449  INFO 29688 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-12-27 17:56:02.452  INFO 29688 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2022-12-27 17:56:02.462  INFO 29688 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-12-27 17:56:02.464  INFO 29688 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Shutdown initiated...
2022-12-27 17:56:02.465  INFO 29688 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Shutdown completed.
2022-12-27 17:56:02.472  INFO 29688 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-12-27 17:56:02.473  INFO 29688 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-3 - Shutdown initiated...
2022-12-27 17:56:02.474  INFO 29688 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-3 - Shutdown completed.

108 tests completed, 1 failed

> Task :test FAILED

FAILURE: Build failed with an exception.
`

Similar failure currently occurs on GitHub Actions too.

@adrianliz could you try to run the test suite locally and let me know what results you get...

**Comment by valentinacupac** [comment]
I am closing this ticket, we can continue on #58 to resolve the open issue.
