### ISSUE TITLE
Fix pitest for multi-module project

### ISSUE THREAD

**Issue by valentinacupac** [valentinacupac/banking-kata-java#69]
The following error started appearing sometime after the modules were split (when moving from monolith to modular monolith)

```
PS C:\Users\valen\GitHub\valentinacupac\banking-kata-java> ./gradlew pitest                                             

> Task :pitest FAILED
12:23:38 PM PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
12:23:38 PM PIT >> INFO : Incremental analysis reduced number of mutations by 0
12:23:38 PM PIT >> INFO : Created  0 mutation test units in pre scan
Exception in thread "main" org.pitest.help.PitHelpError: No mutations found. This probably means there is an issue with either the supplied classpath or filters.
See http://pitest.org for more details.
        at org.pitest.mutationtest.tooling.MutationCoverage.checkMutationsFound(MutationCoverage.java:352)
        at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:132)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:123)
        at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:54)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)
        at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)

FAILURE: Build failed with an exception.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
1 actionable task: 1 executed

```

**Comment by valentinacupac** [comment]
Based on instructions in https://gradle-pitest-plugin.solidsoft.info/ for "Multi-module projects support", the update for `build.gradle` was here:

https://github.com/valentinacupac/banking-kata-java/commit/31b2b8de10cbfb2e4c48b49cf149a252d367d68e#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7
